### PR TITLE
Close button in chatbot

### PR DESCRIPTION
**Pull request by Varsani2520**
i solve the close icon issue #174 
now user can click on close icon then close the chat Bot

### CODE REVIEW

**Comment by Varsani2520** [comment]
@AbhiDiva96 ,please merged it and also add the label

**Comment by AbhiDiva96** [comment]
Your PR conflicting with deployment @Varsani2520

**Comment by Varsani2520** [comment]
ok i try to solved

**Comment by Varsani2520** [comment]
@AbhiDiva96 ,i build the app in local then its sucessful but why i dont know issue in live 
can you send me vercel deployment error screenshot

**Comment by Varsani2520** [comment]
Hi @AbhiDiva96 ,can you send me deployment error

**Comment by AbhiDiva96** [comment]
Screenshot 2024-06-23 021014
hey @Varsani2520 
resolve it

**Comment by Varsani2520** [comment]
Hey @AbhiDiva96  ,i resolve the deployment error now you merged it also add the label

**Comment by AbhiDiva96** [comment]
After closing chatbot toggle got invisible pls add that.
Before 
Screenshot_2024-06-23-10-53-40-04_40deb401b9ffe8e1df2f1cc5ba480b12
 After
Screenshot_2024-06-23-10-53-19-44_40deb401b9ffe8e1df2f1cc5ba480b12

**Comment by Varsani2520** [comment]
Hey @AbhiDiva96 ,i solve the chatbot but i dont know why deployment failed ,in my localhost :
image
can you send me vercel error

**Comment by AbhiDiva96** [comment]
Screenshot_2024-06-23-11-45-45-56_40deb401b9ffe8e1df2f1cc5ba480b12
 Vercel error resolve it @Varsani2520

**Comment by Varsani2520** [comment]
@AbhiDiva96 ,now you are ready to merge 

i resolve the vercel error

**Comment by AbhiDiva96** [comment]
Hey @Varsani2520
 when a user go to 75per website they only get home page not directly chatbot.

If a user want to open chatbot then the pop-up of chatbot should be appear else it will be closed

Create a issue and make a PR accordingly

**Comment by Varsani2520** [comment]
ok

**Pull request merged**
