### PR TITLE
feat: Landing page enhanced [navbar and footer]

### PR DESCRIPTION
**Pull request by RamakrushnaBiswal**
image

image

image

### CODE REVIEW

**Comment by RamakrushnaBiswal** [comment]
@AbhiDiva96 review the PR

**Comment by AbhiDiva96** [comment]
Make it responsive for mobile view use sidebar toggler so that all the header components like login and review page get inside sidebar toggler.
@RamakrushnaBiswal

**Comment by AbhiDiva96** [comment]
hey @RamakrushnaBiswal 
are your working on or not??

**Comment by RamakrushnaBiswal** [comment]
@AbhiDiva96 i am working upon it i will confirm you soon

**Comment by RamakrushnaBiswal** [comment]
image
@AbhiDiva96 review the PR

**Comment by AbhiDiva96** [comment]
Resolved conflict @RamakrushnaBiswal

**Comment by RamakrushnaBiswal** [comment]
@AbhiDiva96 done sir

**Comment by AbhiDiva96** [comment]
Make sure vercel deployment shouldn't be failed

**Comment by RamakrushnaBiswal** [comment]
done @AbhiDiva96

**Comment by AbhiDiva96** [comment]
Why it failing @RamakrushnaBiswal

**Comment by RamakrushnaBiswal** [comment]
don't know @AbhiDiva96

**Comment by AbhiDiva96** [comment]
Hey you design is matching with 75per. Puch and get merge it @RamakrushnaBiswal

**Pull request closed without merging**
