### PR TITLE
Added SignIn and SignUp Backend and Improved UI

### PR DESCRIPTION
**Pull request by SamarthUrane**
Added Backend for SignIn and SignUp for User. Improved UI for pages. 
image
image

image

image
image

### CODE REVIEW

**Comment by SamarthUrane** [comment]
Solved Issue No. #72 Under GSSOC'24. Please merge this to main branch

**Comment by AbhiDiva96** [comment]
## why these are overlaping to each other

Screenshot 2024-06-02 155943
Screenshot 2024-06-02 155932

## why these content of below image is not  flex?
Screenshot 2024-06-02 155938

Screenshot 2024-06-02 155927

**Comment by SamarthUrane** [comment]
I am trying to create a 2 different directories for client and server and I have put all frontend code to client and backend code to server but It is giving conflicts.
what should I do? Should I just put my backend code server.js file directly in root directly which is present in current main branch?

**Comment by AbhiDiva96** [comment]
hey @SamarthUrane 
you have done a good job. Yeah, use Vercel only for frontend to deploy it because Vercel deploy frontend code.
You can use your vercel to deploy it. if it works well with your deployment then push the code here after that all the conflicts will resolve

**Comment by AbhiDiva96** [comment]
Hey @SamarthUrane 
You are not responding. I am closing this PR
thankyou

**Pull request closed without merging**
