### PR TITLE
Added Footer

### PR DESCRIPTION
**Pull request by Hemashree21**
Resolved issue #15 

image

@AbhiDiva96 I have made the changes and the footer is responsive as well. Please check and let me know if any changes are required.

### CODE REVIEW

**Comment by AbhiDiva96** [comment]
@Hemashree21 
make it a one-liner. something like the below architecture

Screenshot 2024-05-28 153954


if your want to add anything extra then make a button type which describes your rest of the section such as  legal page or company

**Comment by AbhiDiva96** [comment]
Why the footer colour is different? and left side padding is not available as like right side?

**Comment by AbhiDiva96** [comment]
## Look all the changes look like ugli UI. Please make it a response and remove the company and legal page name we will take it to the header one.


Design footer UI simple and one liner like navbar as possible.

**Comment by Hemashree21** [comment]
Okay sir

**Comment by Hemashree21** [comment]
image

Sir can you please check now? Is it fine?

**Comment by AbhiDiva96** [comment]
Please change the bg-colour

**Comment by Hemashree21** [comment]
Sir what color should I add?

**Comment by Hemashree21** [comment]
image

I have added it how it was initially sir.

**Comment by AbhiDiva96** [comment]
still footer background different from the header make it one.

Screenshot 2024-05-29 003818

Screenshot 2024-05-29 003810

**Comment by AbhiDiva96** [comment]
we are here to ease the work not increase the work so pls make sure you are changing only your own file.
your code increase our work.

Screenshot 2024-05-29 004529

**Comment by AbhiDiva96** [comment]
make it a one-liner in mobile view also

footer


Screenshot 2024-05-30 102457

**Pull request closed without merging**
