### PR TITLE
Dark / Default + Scroll to top added

### PR DESCRIPTION
**Pull request by Vipullakum007**
i have created

1. ScrollToTopButton.js in component ( Because we need to add in every page )
2. ScrollToTopButton.css for style the component
3. Dark/Default Toggler in heading.js
4 . Added ScrollToTopButton in every page

ScreenShots / Video 

https://github.com/AbhiDiva96/75per/assets/127659443/f274d1b2-1f32-4fab-97e3-921ef64f51e1

### CODE REVIEW

**Comment by Vipullakum007** [comment]
hey @AbhiDiva96 , i have added scroll to top + dark-default toggler (with refresh not changed what theme you choose last ) , please make it level 2 it is little bit tough for me. if you want any change than tell me.

**Comment by AbhiDiva96** [comment]
Hey @Vipullakum007 
It’s not seem according to 75per requirement. Your design is insufficient and it work only on home page not for all the pages. Dark theme should be darkblue and make sure there should be no conflict in PR so that it can easily deploy

**Comment by AbhiDiva96** [comment]
hey @Vipullakum007 
You haven't given any response. I am closing this PR because it conflicting the repo.

**Comment by Vipullakum007** [comment]
hey @AbhiDiva96 , i have made componenent so that anyone made change or add page then you need to add <ScrollToTopButton /> . so that added page make conflicting . i solved that please reopen the PR or i make new one.

**Pull request closed without merging**
