### PR TITLE
Added A Pyq Pages to All the years

### PR DESCRIPTION
**Pull request by Hitesh4278**
Screenshot (1605)

If there is any issue contact me.
Issue no . #2

### CODE REVIEW

**Comment by AbhiDiva96** [comment]
@Hitesh4278 
given architecture would be pyq section page

Screenshot 2024-05-28 171435

**Comment by Hitesh4278** [comment]
> @Hitesh4278 given architecture would be pyq section page
> 
> Screenshot 2024-05-28 171435
> 
> I given you hint. so build like something above img

Basically you want me to add two more section that is of odd semester and of even semester?

**Comment by AbhiDiva96** [comment]
previous section is the combination of bunch of subject in which there are two semester and each semester have 6 subject so design such a way that both semester have 6 subject and 10year pyq paper to download.

**Comment by Hitesh4278** [comment]
image
image
image
Check this. @AbhiDiva96

**Comment by AbhiDiva96** [comment]
yaa it looks good but make sure when the user clicks on odd/even semester button they will get all the 10-year pyq of each subject as it is mentioned in the above architecture which I provided you above.
@Hitesh4278

**Comment by Hitesh4278** [comment]
> yaa it looks good but make sure when the user clicks on odd/even semester button they will get all the 10-year pyq of each subject as it is mentioned in the above architecture which I provided you above. @Hitesh4278

image
I think this is  good and fully responsive.

**Comment by Hitesh4278** [comment]
@AbhiDiva96  are you able to see the latest pull request with the new code i have added ? and please  confirm whether i have to do any other thing to the page ASAP ?

**Comment by Hitesh4278** [comment]
Will you please confirm whether you are going to accept it or reject it?

**Comment by sanjay-kv** [comment]
Hi @AbhiDiva96 Let the contributor know if any issues on this as it was stale for 2 weeks, also it has mentioned to add me to rep via official mail . so I can help them with labels if any missed. thanks.

**Comment by AbhiDiva96** [comment]
hey @Hitesh4278 
due to changes in the main file your file is conflicting during the deployment. so pls clone an updated repo and make change and push it. so that I can merge it

**Pull request closed without merging**
