### PR TITLE
Added a preloader to website #82

### PR DESCRIPTION
**Pull request by dhairyagothi**
i have added a preloader in website please merge the PR 
solved issue : #82 

Uploading Recording 2024-06-12 103526.mp4…

Please merge PR asap @AbhiDiva96

### CODE REVIEW

**Comment by AbhiDiva96** [comment]
make sure when you resolve your feature and issue don't change other 
Screenshot (327)
Screenshot (325)

**Comment by dhairyagothi** [comment]
image

soory for inconvenience caused fixed now

**Comment by dhairyagothi** [comment]
@AbhiDiva96  Please merge the PR

**Comment by AbhiDiva96** [comment]
Hey @dhairyagothi 
Thank for your design but I think 75% didn’t need of preloaded because it giving bad user experience due to latency in accessing the product or material.
Thank you

**Pull request closed without merging**
