### PR TITLE
back button added

### PR DESCRIPTION
**Pull request by AnanyaJain25**
Screenshot 2024-06-06 010236
ADDED BACK BUTTON FIXES Adding return to dashboard Button  #54

### CODE REVIEW

**Comment by AnanyaJain25** [comment]
without back text
Screenshot 2024-06-06 011733

with back
Screenshot 2024-06-06 010236

hey @AbhiDiva96 I am bit confused whether back should be written or not how do you want  it?

**Comment by AnanyaJain25** [comment]
hey @AbhiDiva96 ?

**Comment by AbhiDiva96** [comment]
hey @AnanyaJain25. pls remove back text and give a circle around the arrow.

**Comment by AnanyaJain25** [comment]
image

**Comment by AnanyaJain25** [comment]
@AbhiDiva96 now is this fine?

**Pull request merged**
