### PR TITLE
Added password toggling feature

### PR DESCRIPTION
**Pull request by Ayushmaanagarwal1211**
I added the password toggling button from where user can show or hide the password .

closes : #71 

https://github.com/AbhiDiva96/75per/assets/118350936/46ef8fcf-e9e6-451f-b144-c41e24df3510

### CODE REVIEW

**Comment by Ayushmaanagarwal1211** [comment]
Hii @AbhiDiva96  have a look

**Comment by Ayushmaanagarwal1211** [comment]
Hii @AbhiDiva96  please review it

**Comment by AbhiDiva96** [comment]
hey @Ayushmaanagarwal1211 
your current code is conflicting.
pls write clean code so that it doesn't conflict. so that I can merge it
Screenshot 2024-06-09 121315

Screenshot 2024-06-09 121344

**Comment by Ayushmaanagarwal1211** [comment]
Ok doing

**Pull request closed without merging**
