### PR TITLE
Dark default toggler added

### PR DESCRIPTION
**Pull request by Vipullakum007**
i have created

1. ScrollToTopButton.js in component ( Because we need to add in every page )
2. ScrollToTopButton.css for style the component
3. Dark/Default Toggler in heading.js
4. Added ScrollToTopButton in every page

**Working Video**

https://github.com/AbhiDiva96/75per/assets/127659443/c0293339-9492-49d0-8799-774e220ac858

### CODE REVIEW

**Comment by Vipullakum007** [comment]
hey @AbhiDiva96 , i have resolved conflict s of OLD PR. you can review it.

**Comment by Vipullakum007** [comment]
**NOTE :** hey @AbhiDiva96 , i have made component so that anyone made change or add page then you need to add . so that added page make conflicting . i solved that please reopen the PR or i make new one.

**Comment by Vipullakum007** [comment]
hey @AbhiDiva96 ,please merge ASAP because



> **NOTE :** hey @AbhiDiva96 , i have made component so that anyone made change or add page then you need to add . so that added page make conflicting . i solved that please reopen the PR or i make new one.

**Comment by AbhiDiva96** [comment]
Your code is not clean and not actually supporting 75% design. 
Someone else created a theme toggler pls check out on the site.
@Vipullakum007

**Comment by Vipullakum007** [comment]
hey @AbhiDiva96 , Scroll to Top is working perfect if you want i can add that part only

**Pull request closed without merging**
