### PR TITLE
Login/signup Functionality

### PR DESCRIPTION
**Pull request by nishant0708**
Hey @AbhiDiva96  here is the requested changes with backend folder in this https://github.com/nishant0708/75per-backend/invitations you can clone it .

Solves issue #102

### CODE REVIEW

**Comment by nishant0708** [comment]
Hey @AbhiDiva96  please Assign level to this issue

**Comment by AbhiDiva96** [comment]
Screenshot 2024-06-18 232204

give me access of this branch last-try

**Comment by nishant0708** [comment]
Wait

**Comment by nishant0708** [comment]
https://github.com/nishant0708/75per/invitations

**Comment by nishant0708** [comment]
hey @AbhiDiva96  i am genuinely telling you i have working on it from past 2 week to make this work making folders and all and you know github was giving error please can you please assign it level 2 at least .Sincerely i am requesting you

**Comment by nishant0708** [comment]
@AbhiDiva96 sir please 🙏🙏🙏

**Comment by AbhiDiva96** [comment]
Hey @nishant0708 
Don't worry about labels. 
I have to create a separate folder for both frontend and backend as well so that it look different.
Still your PR of last-try branch didn't add.
No worry I will create one till then work on the same.

**Comment by AbhiDiva96** [comment]
Deploy your last-try branch code to vercel. Is it working or not. Inform me accordingly 
@nishant0708

**Comment by nishant0708** [comment]
https://75per-6jld-baayxckse-nishants-projects-7fc25a7b.vercel.app/ hey @AbhiDiva96  its pyq branch which i deployed
see it is connected to server it will give error for now because i will need to update paths in server but else it will work fine so should i update backend ?????????

**Comment by AbhiDiva96** [comment]
Make me team members so that I can access it @nishant0708

**Comment by nishant0708** [comment]
hey @AbhiDiva96 i dont have pro for vercel so it is asking me for money.

**Pull request merged**
