### PR TITLE
Added Hamburger Menu

### PR DESCRIPTION
**Pull request by Ayushmaanagarwal1211**
I've added the Hamburger Menu for the website  .
closes : #154 

https://github.com/AbhiDiva96/75per/assets/118350936/52e67691-9daf-4655-a846-09db2a28432d

### CODE REVIEW

**Comment by Ayushmaanagarwal1211** [comment]
@AbhiDiva96  Please review this

**Comment by AbhiDiva96** [comment]
Resolve conflict @Ayushmaanagarwal1211 
Screenshot_2024-06-23-12-50-46-94_40deb401b9ffe8e1df2f1cc5ba480b12

**Comment by Ayushmaanagarwal1211** [comment]
Yes i started working on it

**Comment by Ayushmaanagarwal1211** [comment]
> Quite good but make it as popup menu.

@AbhiDiva96  Did you have any image or example like i will create it like that

**Pull request closed without merging**
