### PR TITLE
Chatbot

### LINKED ISSUE #116: [Feature Request]: Enhancing User Engagement with Our New Chatbot Feature
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

 The chatbot will serve as an interactive assistant, providing users with real-time support, information, and assistance tailored to their needs.

### Use Case

Consider a scenario where a user encounters a problem while navigating our platform. Instead of searching through help documentation or contacting support, they can simply interact with the chatbot. The chatbot will guide them through troubleshooting steps, answer questions, and provide assistance in real-time, improving user satisfaction and retention

### Benefits

Improved User Engagement - The chatbot provides a conversational interface that encourages users to interact with our platform more frequently.

### Add ScreenShots

_No response_

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by codercake**
I've added the chatbot with few questions and the syllabus labels. 

**Closes #116** 

image

Let me know if there are any changes to be made.

### CODE REVIEW

**Comment by AbhiDiva96** [comment]
Hey @codercake 
Remove the conflict of PR. So that I can easily merge it

**Comment by codercake** [comment]
removed the conflicts, can you check? @AbhiDiva96

**Comment by AbhiDiva96** [comment]
6CDC90CE-8FF5-4A57-9814-CE18AB96A370

still not resolved

**Comment by codercake** [comment]
can you check it now @AbhiDiva96

**Comment by AbhiDiva96** [comment]
Hey @codercake 
It's nice work but what's the uses of this bot how user can take benefit out of it,?

**Comment by codercake** [comment]
> Hey @codercake It's nice work but what's the uses of this bot how user can take benefit out of it,?

Bssentially, I've included labels prompting users to provide details such as their current academic year. This helps users easily navigate to specific tabs, like Quantum or Lectures/DSA sections.

**Comment by AbhiDiva96** [comment]
Hey @codercake 
Screenshot_2024-06-14-17-58-51-15_40deb401b9ffe8e1df2f1cc5ba480b12

There is some conflict with branch solve then push it.

## commands
Screenshot_2024-06-14-17-59-00-08_40deb401b9ffe8e1df2f1cc5ba480b12

**Comment by AbhiDiva96** [comment]
hey @codercake are you solving it??

**Comment by codercake** [comment]
> hey @codercake are you solving it??

yep, on it!

**Pull request closed without merging**
