### PR TITLE
Added Hamburger Menu 

### PR DESCRIPTION
**Pull request by Ayushmaanagarwal1211**
I've added the Hamburger Menu for the website .
closes : #154 

https://github.com/AbhiDiva96/75per/assets/118350936/b8768151-fda2-43e5-b76a-c50b56818fba

### CODE REVIEW

**Comment by Ayushmaanagarwal1211** [comment]
@AbhiDiva96  I created a new pr please check

**Comment by AbhiDiva96** [comment]
All good. Have you seen the current 75per website some changes taken place.
Your design is good but make it pop like below image and theme toggler is good take it out of the pop-up box.
Screenshot_2024-06-23-13-22-47-38_40deb401b9ffe8e1df2f1cc5ba480b12

**Comment by Ayushmaanagarwal1211** [comment]
Ok I am doing

**Comment by Ayushmaanagarwal1211** [comment]
@AbhiDiva96  Please check i have updated like that 

https://github.com/AbhiDiva96/75per/assets/118350936/d3f509fd-40e9-45d1-a659-7ef86403adf1

**Comment by AbhiDiva96** [comment]
Use background as blur. In your design there is a lack of background. Make background blur@Ayushmaanagarwal1211

**Comment by Ayushmaanagarwal1211** [comment]
ok doing

**Comment by Ayushmaanagarwal1211** [comment]
@AbhiDiva96  I have updated please check is it correct for you or some changes

**Pull request merged**
