### PR TITLE
login and signup validation sucessfully added

### PR DESCRIPTION
**Pull request by Varsani2520**
Hey @AbhiDiva96 ,

i solved the issue #68 ,

`description`:user click on continue button without fill the field then alert message display for filling the field :
`screenshots`:
-  login form:
image

- sign up form :
image

check it and merge it also close the #68 
as well as assign the label

### CODE REVIEW

**Comment by Varsani2520** [comment]
@AbhiDiva96 ,
please check it and merged it ,
i complete a validation in sign up and login form

**Comment by Varsani2520** [comment]
Hey @AbhiDiva96 ,
give a response as well as merged it otherwise i complaint you in gssoc community

**Comment by AbhiDiva96** [comment]
Hey @Varsani2520  
Due to semester examination. I am not able to give proper to time. Pls make patience I will merge it in few time.
Thank you

**Comment by AbhiDiva96** [comment]
Hey @Varsani2520
there is some changes taken place in the repo file. so pls again clone it and do your changes and the push it. due to this the current file is conflicting.

**Comment by Varsani2520** [comment]
@AbhiDiva96 ,check it and merge it

**Comment by AbhiDiva96** [comment]
@Varsani2520  Your PR conflict and denay to deployment on vercel so make sure you are making right PR.

**Comment by Varsani2520** [comment]
Hey @AbhiDiva96 ,i solved the conflict now you can check 
also add the label as per #68

**Pull request merged**
