### PR TITLE
Added a review page

### PR DESCRIPTION
**Pull request by Manav173**
Added customer review page against issue no. #106
Kindly check and merge this PR @AbhiDiva96 .

Added Review Us button in the header :-
image

Review Us page with a button to return to the main page :-
image

Also added a pop up message to display that the form has been submitted :-
image

P.S would really appreciate if you can raise the issue level from 1 to 2/3.

### CODE REVIEW

**Comment by AbhiDiva96** [comment]
Hey @Manav173 
Why there is no submit button for review??
And make it responsible.

Screenshot_2024-06-10-15-00-40-01_40deb401b9ffe8e1df2f1cc5ba480b12

**Comment by Manav173** [comment]
@AbhiDiva96 Have you checked it on laptop ?

**Comment by Manav173** [comment]
Can you raise the issue level from 1 to 2/3.

**Comment by Manav173** [comment]
Can you raise the issue level from 1 to 2/3 @AbhiDiva96 .

**Comment by AbhiDiva96** [comment]
U just added the frontend code, there is absence of backend code. Labels are given accordingly.

**Pull request merged**
