### PR TITLE
Created Dark Mode

### LINKED ISSUE #136: [Feature Request]:  Dark Mode for website
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I will implement the dark mode for the website .

### Use Case

This make the website more attractive 

### Benefits

_No response_

### Add ScreenShots

Screenshot 2024-06-15 230400

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by Ayushmaanagarwal1211**
I have created a dark mode for the website
closes : #136 

Sir i have created a new pr actually this is due to the previously merged pr the about us was overflowing from the navbar but i have fixed it .
You can check if you like it then please try to give 3 level because i did changes and write whole new file for dark mode .

### CODE REVIEW

**Comment by Ayushmaanagarwal1211** [comment]
@AbhiDiva96  thanks for merging and sir if you want i can also raise issue for hamburger menu it may looks good

**Comment by AbhiDiva96** [comment]
Hey @Ayushmaanagarwal1211 
Great work. This PR actually a level3 PR 
don't warry.
I gave you level3 it will help you to boost you ranking

**Comment by AbhiDiva96** [comment]
Ya sure u can. @Ayushmaanagarwal1211

**Comment by Ayushmaanagarwal1211** [comment]
Ok

**Comment by Ayushmaanagarwal1211** [comment]
> Hey @Ayushmaanagarwal1211 Great work. This PR actually a level3 PR don't warry. I gave you level3 it will help you to boost you ranking

Thank you sir

**Pull request merged**
