### PR TITLE
added back button on different pages

### PR DESCRIPTION
**Pull request by Rajput-xv**
issue #165 

Added all the back button with their suitable previous pages for easy navigation for user.

mentioned issue is resolved
kindly look into this.
Hence, merge my PR

@AbhiDiva96 

thank you

### CODE REVIEW

**Comment by Rajput-xv** [comment]
Hello 
@AbhiDiva96 
kindly merge my PR, as i have resolved the issue assigned to me.

**Comment by AbhiDiva96** [comment]
Resolve conflict

**Comment by Rajput-xv** [comment]
> Resolve conflict

Conflicts have been resolved. Kindly check.

**Comment by Rajput-xv** [comment]
Hello @AbhiDiva96 
kindly look and merge the PR.

**Comment by Rajput-xv** [comment]
@AbhiDiva96 
kindly look into this PR.

**Comment by sanjay-kv** [comment]
Hi @AbhiDiva96 Kinldy look into the PR . if its all fine kindly assign label and merge

**Comment by AbhiDiva96** [comment]
@sanjay-kv got it

**Pull request merged**
