### PR TITLE
Added Search Functionality

### PR DESCRIPTION
**Pull request by Ayushmaanagarwal1211**
I have added the search functionality 

closes : #118

I have added the search functionality in all pages where it is needed and for that i have to configure the whole code so please give level 2 or 3 if found it suitable .

https://github.com/AbhiDiva96/75per/assets/118350936/d04d59c6-1f8a-47ec-b9d1-6c6b3474e1d6

### CODE REVIEW

**Comment by AbhiDiva96** [comment]
hey @Ayushmaanagarwal1211 
greate job but make sure some padding and margin in the search bar so that it look user friendly
## your design
Screenshot 2024-06-12 082953
## expected design

**Comment by Ayushmaanagarwal1211** [comment]
Sure Doing

**Comment by Ayushmaanagarwal1211** [comment]
@AbhiDiva96 Can you please check updated

**Comment by AbhiDiva96** [comment]
Make it more attractive use good quality css for responsive.
I can see that in mobile view it is not responsible.

Use a search toggle(🔍) within the search  bar

**Comment by Ayushmaanagarwal1211** [comment]
Ok doing

**Comment by Ayushmaanagarwal1211** [comment]
https://github.com/AbhiDiva96/75per/assets/118350936/3e23c534-90ce-485f-a177-62a027cd2903

@AbhiDiva96  please check

**Comment by Ayushmaanagarwal1211** [comment]
And if you have any suggestion for attractiveness of search bar please let me know i will do like that

**Comment by AbhiDiva96** [comment]
Hey @Ayushmaanagarwal1211 
I already gave you an image above check it out and design accordingly

**Comment by AbhiDiva96** [comment]
I am merging it but needs improvement

**Pull request merged**
