### PR TITLE
Syllabus for Particular Year Displayed

### PR DESCRIPTION
**Pull request by swetha5157**
Issue No:#5 

### Closes Issue #5

**Description**:
When the year is clicked followed by the Syllabus..it displays the syllabus for 8 semesters but it has to be displayed for the selected year's semester(i.e. if the 2nd year is selected, the 3rd and 4th sem has to be displayed). The issue has been resolved by providing correct routing and creating separate folders. Now the output will be when a particular year is selected then the particular semesters will be displayed for syllabus download.

My code follows the guidelines and does not produce any warnings.

**Test**:
 I have tested with all four years and attached the video document below.
 
 I am a GSSoC'24 Contributor.

Screenshots/Video

https://github.com/AbhiDiva96/75per/assets/123291594/a7cfef4b-764c-4a2b-b7ec-089f1b4a2bf1

### CODE REVIEW

**Comment by swetha5157** [comment]
Kindly check this PR @AbhiDiva96

**Comment by AbhiDiva96** [comment]
Screenshot 2024-05-29 204321


remove the underlines @swetha5157

**Comment by swetha5157** [comment]
Shall I create as new issue @AbhiDiva96 ?

**Comment by AbhiDiva96** [comment]
just create here.  I am reopening this issue

**Comment by swetha5157** [comment]
OK @AbhiDiva96

**Comment by AbhiDiva96** [comment]
## why right side of header section taking space in desktop view. Pls fix it
@swetha5157

**Comment by swetha5157** [comment]
Yes @AbhiDiva96 I'll make it centered..

**Comment by swetha5157** [comment]
Hi @AbhiDiva96 
Since the PR is closed my commits for the changes mentioned were not displayed.
But I have made the changes..
Screenshot 2024-05-31 093653
**Video:**

https://github.com/AbhiDiva96/75per/assets/123291594/497a87db-1e01-4e50-880e-59b211b75ca1

**Pull request merged**
