### PR TITLE
Floating animation added

### PR DESCRIPTION
**Pull request by Damini2004**
#258 
Added the animation.

### CODE REVIEW

**Comment by Damini2004** [comment]
@AbhiDiva96  Gothrough the PR and suitable level.

**Comment by AbhiDiva96** [comment]
@Damini2004 
Fix the conflict

**Comment by Damini2004** [comment]
@AbhiDiva96 review again.

**Comment by AbhiDiva96** [comment]
Your commit creates difficulties while deploying. Pls improve it

**Comment by Damini2004** [comment]
@AbhiDiva96 can help me how to improve it ?

**Pull request closed without merging**
