### PR TITLE
chatbot implementation

### LINKED ISSUE #116: [Feature Request]: Enhancing User Engagement with Our New Chatbot Feature
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

 The chatbot will serve as an interactive assistant, providing users with real-time support, information, and assistance tailored to their needs.

### Use Case

Consider a scenario where a user encounters a problem while navigating our platform. Instead of searching through help documentation or contacting support, they can simply interact with the chatbot. The chatbot will guide them through troubleshooting steps, answer questions, and provide assistance in real-time, improving user satisfaction and retention

### Benefits

Improved User Engagement - The chatbot provides a conversational interface that encourages users to interact with our platform more frequently.

### Add ScreenShots

_No response_

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by codercake**
**fixes #116** 

image

### CODE REVIEW

**Comment by codercake** [comment]
could you review the PR @AbhiDiva96

**Comment by AbhiDiva96** [comment]
Why your vercel deployment failing?? @codercake

**Comment by codercake** [comment]
> Why your vercel deployment failing?? @codercake
it is running successfully on my system, you can refer the screenshot above.

**Comment by codercake** [comment]
kindly add the labels - 
GSSOC’24 
gssoc
level that is suitable for the raised PR

**Comment by codercake** [comment]
can you review the pr? @AbhiDiva96 

> kindly add the labels - GSSOC’24 gssoc level that is suitable for the raised PR

**Comment by AbhiDiva96** [comment]
Why your close tab functionality not working pls correct it. @codercake 
Screenshot_2024-06-19-13-09-26-64_40deb401b9ffe8e1df2f1cc5ba480b12

-

**Comment by AbhiDiva96** [comment]
@codercake 
Update YOUR all the PR with level.

**Pull request merged**
