### PR TITLE
Feature: build backend of User Authentication #11

### PR DESCRIPTION
**Pull request by nishant0708**
Feature: build backend of User Authentication #11
-ADDED A SERVER.js file for user Authentication.
-Used MongoDb and nodejs for backend
-For USING
   -set up Google cloud credentials
   In Server.js 
-Add Mongo db Url
-Add client Id and Client Secret Key
-Also Added SignIn/SignUp with Google Button

https://github.com/AbhiDiva96/75per/assets/101548649/da6182ff-5d7a-4cd1-b4ff-90e9c9bcff17

### CODE REVIEW

**Comment by AbhiDiva96** [comment]
Hey @nishant0708 
You have done great work. but one things is lacked is that In the database don't save the password of the user in direct way. use jwt token authentication so that no one can assess the password of the user. enhance it

**Comment by nishant0708** [comment]
Now check latest Commit 
Screenshot 2024-05-29 210326

**Comment by nishant0708** [comment]
It is working fine and please can you let me know changes in mu other prs as well

**Comment by AbhiDiva96** [comment]
create signup/singin frontend page something like the below page and use  the colour of home page.
don't change the content of the page change only frontend design.
Screenshot 2024-05-28 120422

**Comment by nishant0708** [comment]
Hey is it a new issue??  Or should I continue ue to add commits in same branch

**Comment by AbhiDiva96** [comment]
hey @nishant0708. make a separate folder for the backend. don't mesh up thing in frontend

**Comment by nishant0708** [comment]
Actually I created Seperate Backend Folder Only At first But I Was Not Able To Push it Which Caused A problem 
image
 see But I was Not Able to push it so if you can tell how to do that i will do it immediately

**Comment by nishant0708** [comment]
And I cant EDIT YOUR Directory structure Right So It Have to be Done by you . But if there is any way that we can do it and i am unaware of it please tell me I will do it .Sorry For Inconvenience sir

**Pull request merged**
