### PR TITLE
chatbot working 

### PR DESCRIPTION
**Pull request by codercake**
fixes #164

### CODE REVIEW

**Comment by AbhiDiva96** [comment]
hey @codercake 
sorry to say but your PR doesn't give permit to merge. figure out it
Screenshot 2024-06-22 000226
Screenshot 2024-06-22 000221

**Comment by AbhiDiva96** [comment]
hey @codercake 
any update??

**Comment by codercake** [comment]
checkout the PR @AbhiDiva96

**Comment by codercake** [comment]
> hey @codercake any update??

can you checkout the updates? @AbhiDiva96

**Comment by codercake** [comment]
> hey @codercake any update??

can you review the PR? @AbhiDiva96

**Pull request closed without merging**
